Repository Glue42/core, pull requests merged in 2020-09, with the labels that each got.

#128 Extended the end-to-end testing environment with support application manipulation.
  .gitignore
  e2e/config.js
  e2e/config/apps/coreSupport/index.html
  e2e/config/apps/coreSupport/index.js
  e2e/config/apps/supportApp/index.html
  e2e/config/apps/supportApp/index.js
  e2e/config/glue.config.dev.json
  e2e/config/glue/glue.config.json
  e2e/config/gtf.js
  e2e/config/gtf/agm.ts
  e2e/config/gtf/core.ts
  e2e/config/gtf/index.ts
  e2e/config/gtf/types.ts
  e2e/config/gtf/аpp.ts
  e2e/tests/Play/play.spec.js
  package-lock.json
  package.json
Labels: tag: underlying tools

#129 Bugfix: remote apps cannot open in workspaces
  packages/web/src/app-manager/main.ts
  packages/workspaces-app/src/layouts.ts
  packages/workspaces-app/src/manager.ts
Labels: tag: bug fix

#130 Add a way for @glue42/fdc3 to accept the application's name
  docs/core/03_capabilities/99_fdc3-compliance/fdc3-compliance.md
  live-examples/app-manager/app-manager-events/app-b/index.js
  packages/fdc3/src/channels/channels.ts
  packages/fdc3/src/main.ts
  packages/fdc3/src/utils.ts
  packages/fdc3/src/windowtype.d.ts
Labels: tag: bug fix, tag: documentation

#132 Use `glue.contexts.setPaths()` instead of `glue.contexts.update()` when updating a channel
  packages/web/src/channels/contexts.ts
  packages/web/src/channels/main.ts
Labels: tag: enhancement

#137 Fix a bug where the channel's data is undefined instead of an empty object
  packages/web/src/channels/contexts.ts
Labels: tag: bug fix

#135 Fix the application start resolve condition
  packages/web/src/app-manager/application.ts
Labels: tag: bug fix

#138 Add input validation to the @glue42/core's Contexts API
  docs/core/04_core-concepts/03_glue42-client/03_react/react.md
  e2e/tests/channels/API/join.spec.js
  packages/core/src/contexts/contextsModule.ts
  packages/web/src/channels/main.ts
  packages/web/web.d.ts
Labels: tag: bug fix, tag: documentation, tag: enhancement
