Repository Glue42/core, pull requests merged in 2020-07, with the labels that each got.

#105 Edited Channels and Application Management docs.
  docs/core/03_capabilities/01_overview/overview.md
  docs/core/03_capabilities/02_application-management/application-management.md
  docs/core/03_capabilities/03_shared-contexts/shared-contexts.md
  docs/core/03_capabilities/04_channels/channels.md
  docs/core/03_capabilities/05_interop/interop.md
  docs/core/03_capabilities/06_application-management/application-management.md
  docs/core/03_capabilities/06_window-management/window-management.md
  docs/core/04_core-concepts/02_environment/01_overview/overview.md
  tutorials/guides/02_core/01_javascript/javascript.md
  tutorials/javascript/solution/clients/index.html
  tutorials/javascript/solution/clients/index.js
  tutorials/javascript/solution/stocks/details/index.html
  tutorials/javascript/solution/stocks/details/index.js
  tutorials/javascript/solution/stocks/index.html
  tutorials/javascript/solution/stocks/index.js
  tutorials/javascript/start/Clients/index.js
  tutorials/javascript/start/Stocks/index.js
Labels: tag: documentation

#104 Add process controller for karma and gluec
  e2e/index.js
  package-lock.json
  package.json
Labels: tag: underlying tools

#110 Extend the CLI with workspaces functionalities
  packages/cli-core/package-lock.json
  packages/cli-core/src/builder/controller.ts
  packages/cli-core/src/cli.ts
  packages/cli-core/src/commands.ts
  packages/cli-core/src/config/cli.config.d.ts
  packages/cli-core/src/config/config-decoders.ts
  packages/cli-core/src/config/controller.ts
  packages/cli-core/src/config/user.config.d.ts
  packages/cli-core/src/defaults.ts
  packages/cli-core/src/initiate/controller.ts
  packages/cli-core/src/initiate/index.ts
  packages/cli-core/src/server/server.ts
  packages/cli-core/src/workspaces/controller.ts
  packages/cli-core/src/workspaces/index.ts
Labels: tag: new feature

#113 extend e2e process controller functionality
  e2e/config.js
  e2e/config.json
  e2e/config/karma.conf.js
  e2e/index.js
  e2e/ready-conditions/base-polling.js
  e2e/testServer/exampleServer.js
Labels: tag: underlying tools

#114 React tutorial missing details
  tutorials/guides/02_core/02_react/react.md
  tutorials/react/solution/Clients/src/ChannelSelectorWidget.js
  tutorials/react/solution/Clients/src/constants.js
  tutorials/react/solution/Stocks/src/ChannelSelectorWidget.js
  tutorials/react/solution/Stocks/src/StockDetails.jsx
  tutorials/react/solution/Stocks/src/Stocks.jsx
  tutorials/react/solution/Stocks/src/constants.js
  tutorials/react/start/Clients/src/ChannelSelectorWidget.js
  tutorials/react/start/Clients/src/constants.js
  tutorials/react/start/Stocks/src/ChannelSelectorWidget.js
  tutorials/react/start/Stocks/src/StockDetails.jsx
  tutorials/react/start/Stocks/src/constants.js
Labels: tag: documentation
