Repository Glue42/core, pull requests merged in 2020-04, with the labels that each got.

#45 build(rollup.config): output names
  packages/react-hooks/jest.config.js
  packages/react-hooks/package.json
  packages/react-hooks/react-hooks.d.ts
  packages/react-hooks/rollup.config.js
  packages/react-hooks/src/Glue.tsx
  packages/react-hooks/src/useGlue.ts
  tutorials/react/solution/Clients/package.json
  tutorials/react/solution/Stocks/package.json
Labels: tag: enhancement

#44 Migrate to npm
  .eslintrc.json
  .gitignore
  CONTRIBUTING.md
  gulpfile.js
  lerna.json
  package-lock.json
  package.json
  packages/cli-core/package-lock.json
  packages/cli-core/package.json
  packages/core/package-lock.json
  packages/core/package.json
  packages/react-hooks/.eslintrc.js
  packages/react-hooks/.gitignore
  packages/react-hooks/.prettierrc.json
  packages/react-hooks/package-lock.json
  packages/react-hooks/package.json
  packages/web/package-lock.json
  packages/web/package.json
  packages/worker-web/package-lock.json
  packages/worker-web/package.json
  scripts/audit/audit.js
  scripts/audit/index.js
  scripts/preversion/version-checker.js
  scripts/shared/packages-json-helpers.js
Labels: tag: enhancement

#46 doc: Fix documentation errors 📝
  docs/core/01_what-is-glue42-core/01_introduction/introduction.md
  docs/core/01_what-is-glue42-core/02_capabilities/capabilities.md
  docs/core/01_what-is-glue42-core/03_core-concepts/01_environment/environment.md
  docs/core/01_what-is-glue42-core/03_core-concepts/02_glue42-client/client.md
  docs/core/01_what-is-glue42-core/03_core-concepts/03_cli/cli.md
  docs/core/02_getting-started/01_quick-start/quick-start.md
  docs/core/02_getting-started/02_setting-environment/01_single-application/single-application.md
  docs/core/02_getting-started/02_setting-environment/02_multiple-applications/multiple-applications.md
  docs/core/02_getting-started/02_setting-environment/03_manual/manual.md
  docs/core/02_getting-started/02_setting-environment/04_advanced/advanced.md
  docs/core/02_getting-started/03_setting-application/01_vanilla-js/vanilla.md
  docs/core/02_getting-started/03_setting-application/02_react/react.md
  docs/core/02_getting-started/04_project-deployment/deploy.md
  docs/core/03_tutorials/tutorials.md
  packages/react-hooks/README.md
  packages/web/readme.md
  packages/web/web.d.ts
  packages/worker-web/README.md
Labels: tag: documentation

#47 test(react-hooks): add jest typings
  packages/react-hooks/jest.config.js
  packages/react-hooks/overrides/jest/index.d.ts
  packages/react-hooks/package-lock.json
  packages/react-hooks/package.json
  packages/react-hooks/tests/GlueProvider.spec.tsx
  packages/react-hooks/tests/tsconfig.json
  packages/react-hooks/tsconfig.json
Labels: tag: enhancement

#49 docs: Fix vanilla-js tutorial guide errors 📚; refactor: Fix vanilla-js tutorial errors 📦
  docs/core/01_what-is-glue42-core/03_core-concepts/03_cli/cli.md
  docs/core/02_getting-started/01_quick-start/quick-start.md
  docs/core/02_getting-started/03_setting-application/01_vanilla-js/vanilla.md
  tutorials/guides/vanilla-js/vanilla.md
  tutorials/react/start/Stocks/src/Stocks.jsx
  tutorials/vanilla-js/solution/clients/index.js
  tutorials/vanilla-js/solution/package.json
  tutorials/vanilla-js/solution/stocks/details/details.js
  tutorials/vanilla-js/solution/stocks/index.js
  tutorials/vanilla-js/start/Clients/index.html
  tutorials/vanilla-js/start/Stocks/details/details.js
  tutorials/vanilla-js/start/Stocks/index.js
  tutorials/vanilla-js/start/package.json
Labels: tag: documentation

#50 Added readme texts for cli-core and web packages
  packages/cli-core/README.md
  packages/web/readme.md
Labels: tag: documentation

#52 Fixed an issue where the CLI `build` will produce a .js config file, instead of .json
  packages/cli-core/src/builder/controller.ts
Labels: tag: bug fix

#53 docs: Fix react tutorial guide errors 📚; refactor: Fix react tutorial errors 📦
  docs/core/01_what-is-glue42-core/02_capabilities/capabilities.md
  tutorials/guides/react/react.md
  tutorials/guides/vanilla-js/vanilla.md
  tutorials/react/solution/Clients/src/glue.js
  tutorials/react/solution/Clients/src/setupProxy.js
  tutorials/react/solution/Stocks/src/setupProxy.js
  tutorials/react/solution/package.json
  tutorials/react/start/Clients/src/constants.js
  tutorials/react/start/Stocks/src/constants.js
  tutorials/vanilla-js/solution/package-lock.json
  tutorials/vanilla-js/solution/package.json
Labels: tag: documentation

#54 fix: Fix a bug where the node process hangs on MacOS 🐛
  packages/cli-core/src/cli.ts
Labels: tag: bug fix

#57 Added `version` command to the CLI, which returns the currently installed version of the package
  packages/cli-core/package.json
  packages/cli-core/src/commands.ts
  packages/cli-core/src/config/cli.config.d.ts
  packages/cli-core/src/config/controller.ts
  packages/cli-core/src/version/controller.ts
  packages/cli-core/src/version/index.ts
Labels: tag: new feature

#58 feat: Allow the react tutorial solution to be served from the file system ✨; docs: Add instructions on how to serve the react tutorial solution from the file system 📚
  tutorials/guides/react/react.md
  tutorials/react/solution/Clients/package.json
  tutorials/react/solution/Clients/public/manifest.json
  tutorials/react/solution/Clients/src/Clients.jsx
  tutorials/react/solution/Clients/src/constants.js
  tutorials/react/solution/Clients/src/serviceWorker.js
  tutorials/react/solution/Clients/src/setupProxy.js
  tutorials/react/solution/Stocks/package.json
  tutorials/react/solution/Stocks/public/manifest.json
  tutorials/react/solution/Stocks/src/Stocks.jsx
  tutorials/react/solution/Stocks/src/constants.js
  tutorials/react/solution/Stocks/src/serviceWorker.js
  tutorials/react/solution/Stocks/src/setupProxy.js
  tutorials/react/start/Clients/package.json
  tutorials/react/start/Clients/public/manifest.json
  tutorials/react/start/Clients/src/Clients.jsx
  tutorials/react/start/Clients/src/constants.js
  tutorials/react/start/Clients/src/serviceWorker.js
  tutorials/react/start/Clients/src/setupProxy.js
  tutorials/react/start/Stocks/package.json
  tutorials/react/start/Stocks/public/manifest.json
  tutorials/react/start/Stocks/src/Stocks.jsx
  tutorials/react/start/Stocks/src/constants.js
  tutorials/react/start/Stocks/src/serviceWorker.js
  tutorials/react/start/Stocks/src/setupProxy.js
Labels: tag: enhancement

#64 Bugfix/issue 62
  packages/core/glue.d.ts
  packages/core/src/interop/client/client.ts
  packages/core/src/interop/client/repository.ts
  packages/core/src/interop/client/types.ts
  packages/core/src/interop/instance.ts
  packages/core/src/interop/interop.ts
  packages/core/tests/interop/methods.ts
  packages/core/tests/typings/main.ts
Labels: tag: bug fix
