Repository Glue42/core, pull requests merged in 2020-06, with the labels that each got.

#81 live-examples - applications loaded in iframes on default page
  docs/core/03_capabilities/04_window-management/window-management.md
  live-examples/contexts/context-discovery/index.html
  live-examples/contexts/context-get-set/index.html
  live-examples/contexts/context-subscription/index.html
  live-examples/interop/basic-interop/index.html
  live-examples/interop/invocation-target/index.html
  live-examples/interop/method-discovery-by-event/index.html
  live-examples/interop/method-discovery-by-name/index.html
  live-examples/interop/server-discovery/index.html
  live-examples/interop/stream-events/index.html
  live-examples/interop/stream-pub-sub/index.html
  live-examples/interop/stream-subscription-request/index.html
  live-examples/windows/window-events/index.html
  live-examples/windows/window-opening/index.html
Labels: tag: documentation

#84 Extend ReactJS documentation and tutorial with channels
  tutorials/guides/react/react.md
  tutorials/react/solution/Clients/package-lock.json
  tutorials/react/solution/Clients/package.json
  tutorials/react/solution/Clients/src/ChannelSelectorWidget.js
  tutorials/react/solution/Clients/src/Clients.jsx
  tutorials/react/solution/Clients/src/constants.js
  tutorials/react/solution/Clients/src/glue.js
  tutorials/react/solution/Stocks/package-lock.json
  tutorials/react/solution/Stocks/package.json
  tutorials/react/solution/Stocks/src/ChannelSelectorWidget.js
  tutorials/react/solution/Stocks/src/StockDetails.jsx
  tutorials/react/solution/Stocks/src/Stocks.jsx
  tutorials/react/solution/Stocks/src/constants.js
  tutorials/react/solution/Stocks/src/glue.js
  tutorials/react/solution/glue.config.json
  tutorials/react/start/Clients/package.json
  tutorials/react/start/Clients/src/ChannelSelectorWidget.js
  tutorials/react/start/Stocks/package.json
  tutorials/react/start/Stocks/src/ChannelSelectorWidget.js
Labels: tag: documentation

#86 feat: Make the Channels API compatible with the G4E one ✨
  packages/web/src/web.ts
  packages/web/tests/channels.ts
  packages/web/tests/initializer.ts
  packages/web/web.d.ts
Labels: tag: enhancement

#87 Update the documentation, live-examples and tutorials with the new Channels API initialization
  docs/core/03_capabilities/05_channels/channels.md
  live-examples/channels/channels-angular-ui/App/package-lock.json
  live-examples/channels/channels-angular-ui/App/package.json
  live-examples/channels/channels-angular-ui/App/src/app/app.module.ts
  live-examples/channels/channels-navigation/lib/web.umd.min.js
  live-examples/channels/channels-navigation/scripts/glue-utils.js
  live-examples/channels/channels-pub-sub/lib/web.umd.min.js
  live-examples/channels/channels-pub-sub/scripts/glue-utils.js
  live-examples/channels/channels-react-ui/App/package-lock.json
  live-examples/channels/channels-react-ui/App/package.json
  live-examples/channels/channels-react-ui/App/src/index.js
  live-examples/channels/channels-vanilla-js-ui/app-a/index.js
  live-examples/channels/channels-vanilla-js-ui/lib/web.umd.min.js
  live-examples/channels/channels-vanilla-js-ui/scripts/glue-utils.js
  live-examples/contexts/context-discovery/lib/web.umd.min.js
  live-examples/contexts/context-get-set/lib/web.umd.min.js
  live-examples/contexts/context-subscription/lib/web.umd.min.js
  live-examples/interop/basic-interop/lib/web.umd.min.js
  live-examples/interop/invocation-target/lib/web.umd.min.js
  live-examples/interop/method-discovery-by-event/lib/web.umd.min.js
  live-examples/interop/method-discovery-by-name/lib/web.umd.min.js
  live-examples/interop/server-discovery/lib/web.umd.min.js
  live-examples/interop/stream-events/lib/web.umd.min.js
  live-examples/interop/stream-pub-sub/lib/web.umd.min.js
  live-examples/interop/stream-subscription-request/lib/web.umd.min.js
  live-examples/windows/window-events/lib/web.umd.min.js
  live-examples/windows/window-opening/lib/web.umd.min.js
  packages/web/tests/channels.ts
  tutorials/angular/solution/clients/package-lock.json
  tutorials/angular/solution/clients/package.json
  tutorials/angular/solution/stocks/package-lock.json
  tutorials/angular/solution/stocks/package.json
  tutorials/guides/react/react.md
  tutorials/guides/vanilla-js/vanilla.md
  tutorials/react/solution/Clients/package-lock.json
  tutorials/react/solution/Clients/package.json
  tutorials/react/solution/Clients/src/index.js
  tutorials/react/solution/Stocks/package-lock.json
  tutorials/react/solution/Stocks/package.json
  tutorials/react/solution/Stocks/src/index.js
  tutorials/vanilla-js/solution/clients/index.js
  tutorials/vanilla-js/solution/lib/web.umd.min.js
  tutorials/vanilla-js/solution/stocks/index.js
  tutorials/vanilla-js/start/lib/web.umd.min.js
Labels: tag: documentation

#89 style: Change the styling of the channels live-examples and VanillaJS Channel Selector Widget UI 💎
  live-examples/channels/channels-navigation/scripts/utils.js
  live-examples/channels/channels-pub-sub/app-a/index.html
  live-examples/channels/channels-pub-sub/app-a/index.js
  live-examples/channels/channels-pub-sub/app-b/index.html
  live-examples/channels/channels-pub-sub/glue.config.json
  live-examples/channels/channels-pub-sub/glue/glue.config.json
  live-examples/channels/channels-pub-sub/scripts/utils.js
  live-examples/channels/channels-vanilla-js-ui/scripts/utils.js
  tutorials/vanilla-js/solution/lib/channelSelectorWidget.js
  tutorials/vanilla-js/start/lib/channelSelectorWidget.js
Labels: tag: documentation

#98 Renamed tutorials folder and edited title configs
  tutorials/guides/02_core/01_javascript/config.json
  tutorials/guides/02_core/01_javascript/javascript.md
  tutorials/guides/02_core/02_react/config.json
  tutorials/guides/02_core/02_react/react.md
  tutorials/guides/02_core/03_angular/angular.md
  tutorials/guides/02_core/03_angular/config.json
  tutorials/guides/02_core/config.json
  tutorials/guides/core/config.json
Labels: tag: documentation

#100 fix: Fix an issue where appManager is required 🐛
  packages/web/src/web.ts
  packages/web/src/windows/startup.ts
Labels: tag: bug fix

#102 e2e tests setup and configuration
  e2e/config.json
  e2e/config/glue.config.dev.json
  e2e/config/glue.config.json
  e2e/config/glue/gateway-web.js
  e2e/config/glue/gtf.js
  e2e/config/glue/web.umd.js
  e2e/config/glue/worker.js
  e2e/config/karma.conf.js
  e2e/tests/Example/example.spec.js
  package-lock.json
  package.json
Labels: tag: underlying tools
