Repository Glue42/core, pull requests merged in 2020-10, with the labels that each got.

#141 Implement an Intents API (TODO: Tests, Typings explanation, Documentation, Live examples and Tutorial)
  packages/fdc3/package-lock.json
  packages/fdc3/package.json
  packages/fdc3/src/agent.ts
  packages/fdc3/src/channels/channels.ts
  packages/fdc3/src/utils.ts
  packages/ng/package-lock.json
  packages/ng/package.json
  packages/react-hooks/package-lock.json
  packages/react-hooks/package.json
  packages/web/package-lock.json
  packages/web/package.json
  packages/web/src/intents/main.ts
  packages/web/src/intents/types.ts
  packages/web/src/shared/decoders/app-manager.ts
  packages/web/src/shared/decoders/intents.ts
  packages/web/src/types.ts
  packages/web/src/web.ts
  packages/web/web.d.ts
Labels: tag: new feature

#143 Implement workspaces events
  e2e/config/gtf/index.ts
  e2e/tests/Workspaces/API/createWorkspace.spec.js
  e2e/tests/Workspaces/API/layouts/onRemoved.spec.js
  e2e/tests/Workspaces/API/layouts/onSaved.spec.js
  e2e/tests/Workspaces/API/onFrameClosed.spec.js
  e2e/tests/Workspaces/API/onFrameOpened.spec.js
  e2e/tests/Workspaces/API/onWindowAdded.spec.js
  e2e/tests/Workspaces/API/onWindowLoaded.spec.js
  e2e/tests/Workspaces/API/onWindowRemoved.spec.js
  e2e/tests/Workspaces/API/onWorkspaceClosed.spec.js
  e2e/tests/Workspaces/API/onWorkspaceOpened.spec.js
  e2e/tests/Workspaces/Frame/onClosed.spec.js
  e2e/tests/Workspaces/Frame/onWindowLoaded.spec.js
  e2e/tests/Workspaces/Frame/onWorkspaceClosed.spec.js
  e2e/tests/Workspaces/Frame/onWorkspaceOpened.spec.js
  e2e/tests/Workspaces/Parent/addWindow.spec.js
  e2e/tests/Workspaces/Workspace/addWindow.spec.js
  e2e/tests/Workspaces/Workspace/close.spec.js
  e2e/tests/Workspaces/Workspace/getAllWindows.spec.js
  e2e/tests/Workspaces/Workspace/onClosed.spec.js
  e2e/tests/Workspaces/Workspace/onWindowLoaded.spec.js
  packages/web/src/layouts/constants.ts
  packages/web/src/layouts/controller.ts
  packages/web/src/layouts/main.ts
  packages/web/src/layouts/types.ts
  packages/web/src/windows/remote.ts
  packages/web/web.d.ts
  packages/workspaces-api/src/communication/bridge.ts
  packages/workspaces-api/src/communication/constants.ts
  packages/workspaces-api/src/communication/core-frame-utils.ts
  packages/workspaces-api/src/communication/interop-transport.ts
  packages/workspaces-api/src/controllers/base.ts
  packages/workspaces-api/src/controllers/core.ts
  packages/workspaces-api/src/controllers/enterprise.ts
  packages/workspaces-api/src/main.ts
  packages/workspaces-api/src/models/frame.ts
  packages/workspaces-api/src/models/window.ts
  packages/workspaces-api/src/models/workspace.ts
  packages/workspaces-api/src/shared/decoders.ts
  packages/workspaces-api/src/shared/ioc.ts
  packages/workspaces-api/src/types/controller.ts
  packages/workspaces-api/src/types/glue.ts
  packages/workspaces-api/src/types/protocol.ts
  packages/workspaces-api/src/types/subscription.ts
  packages/workspaces-api/workspaces.d.ts
  packages/workspaces-app/src/index.ts
  packages/workspaces-app/src/interop/facade.ts
  packages/workspaces-app/src/interop/types.ts
  packages/workspaces-app/src/layout/controller.ts
  packages/workspaces-app/src/layout/stateResolver.ts
  packages/workspaces-app/src/layouts.ts
  packages/workspaces-app/src/manager.ts
  packages/workspaces-app/src/types/events.ts
Labels: tag: new feature

#144 Add optional icon and caption properties to the Application interface
  docs/core/04_core-concepts/02_environment/01_overview/overview.md
  e2e/config.js
  e2e/config/glue/gateway-web.js
  e2e/config/glue/glue.config.json
  e2e/config/gtf.js
  e2e/config/gtf/app.ts
  e2e/config/gtf/appManager.ts
  e2e/config/gtf/core.ts
  e2e/config/gtf/index.ts
  e2e/config/gtf/types.ts
  live-examples/channels/channels-angular-ui/App/src/app/app.component.html
  package.json
  packages/fdc3/package-lock.json
  packages/fdc3/package.json
  packages/fdc3/src/channels/channels.ts
  packages/ng/package-lock.json
  packages/ng/package.json
  packages/react-hooks/package-lock.json
  packages/react-hooks/package.json
  packages/web/package-lock.json
  packages/web/package.json
  packages/web/src/app-manager/application.ts
  packages/web/src/app-manager/main.ts
  packages/web/src/app-manager/types.ts
  packages/web/src/glue.config.d.ts
  packages/web/src/intents/main.ts
  packages/web/src/intents/types.ts
  packages/web/src/shared/decoders/app-manager.ts
  packages/web/web.d.ts
  tutorials/angular/solution/clients/src/app/channel-select/channel-select.component.html
  tutorials/angular/solution/stocks/src/app/channel-select/channel-select.component.html
  tutorials/angular/start/clients/src/app/channel-select/channel-select.component.html
  tutorials/angular/start/stocks/src/app/channel-select/channel-select.component.html
Labels: dependencies, tag: bug fix, tag: documentation, tag: enhancement, tag: new feature

#139 move tests from enterprise to core
  e2e/config/apps/coreSupport/index.js
  e2e/config/gtf.js
  e2e/config/gtf/agm.ts
  e2e/config/gtf/app.ts
  e2e/config/gtf/core.ts
  e2e/config/gtf/index.ts
  e2e/config/gtf/types.ts
  e2e/tests/Play/play.spec.js
  e2e/tests/agm/invoke.spec.js
  e2e/tests/agm/methodAdded.spec.js
  e2e/tests/agm/methodRemoved.spec.js
  e2e/tests/agm/methods.spec.js
  e2e/tests/agm/methodsForInstance.spec.js
  e2e/tests/agm/properties.spec.js
  e2e/tests/agm/register.spec.js
  e2e/tests/agm/registerAsync.spec.js
  e2e/tests/agm/unregister.spec.js
Labels: tag: enhancement

#145 Change `findIntent()` and `findIntentsByContext()` to return only the app intents and the dynamic instance intents
  .gitignore
  e2e/config/gtf.js
  packages/fdc3/src/agent.ts
Labels: tag: enhancement

#147 Add an optional requestTimeout property to the RemoteSource interface
  docs/core/03_capabilities/02_application-management/application-management.md
  docs/core/03_capabilities/99_fdc3-compliance/fdc3-compliance.md
  docs/core/04_core-concepts/02_environment/01_overview/overview.md
  packages/web/src/app-manager/main.ts
  packages/web/src/glue.config.d.ts
  packages/web/src/layouts/stores/json.ts
  packages/web/src/utils/index.ts
Labels: tag: documentation, tag: enhancement

#149 Add tests for all appManager methods
  e2e/config.js
  e2e/config/apps/coreSupport/index.html
  e2e/config/apps/shared/logger.js
  e2e/config/glue.config.dev.json
  e2e/config/glue/glue.config.json
  e2e/config/gtf/appManager.ts
  e2e/config/gtf/channels.ts
  e2e/config/gtf/connection.ts
  e2e/config/gtf/core.ts
  e2e/config/gtf/index.ts
  e2e/config/gtf/logger.ts
  e2e/config/gtf/types.ts
  e2e/config/karma.conf.js
  e2e/remote-source/index.js
  e2e/tests/app-manager/API/application.spec.js
  e2e/tests/app-manager/API/applications.spec.js
  e2e/tests/app-manager/API/instances.spec.js
  e2e/tests/app-manager/API/onAppAdded.spec.js
  e2e/tests/app-manager/API/onAppChanged.spec.js
  e2e/tests/app-manager/API/onAppRemoved.spec.js
  e2e/tests/app-manager/API/onInstanceStarted.spec.js
  e2e/tests/app-manager/API/onInstanceStopped.spec.js
  e2e/tests/app-manager/API/properties.spec.js
  e2e/tests/app-manager/Application/onInstanceStarted.spec.js
  e2e/tests/app-manager/Application/onInstanceStopped.spec.js
  e2e/tests/app-manager/Application/properties.spec.js
  e2e/tests/app-manager/Application/start.spec.js
  e2e/tests/app-manager/Instance/properties.spec.js
  e2e/tests/app-manager/Instance/stop.spec.js
  e2e/tests/app-manager/initialization.spec.js
  e2e/tests/channels/API/get.spec.js
  e2e/tests/channels/API/publish.spec.js
  e2e/tests/channels/API/subscribe.spec.js
  e2e/tests/channels/API/subscribeFor.spec.js
  e2e/tests/interop/invoke.spec.js
  e2e/tests/interop/methodAdded.spec.js
  package-lock.json
  package.json
  packages/fdc3/src/agent.ts
  packages/fdc3/src/main.ts
  packages/web/src/app-manager/application.ts
  packages/web/src/app-manager/instance.ts
  packages/web/src/app-manager/main.ts
  packages/web/src/app-manager/my.ts
  packages/web/src/control/control.ts
  packages/web/src/shared/decoders/intents.ts
  packages/web/src/web.ts
  packages/web/src/windows/main.ts
  packages/web/src/windows/startup.ts
  packages/web/web.d.ts
Labels: tag: bug fix

#150 Fix a race where `stop()` resolves before the application is removed from the instances array
  e2e/config/gtf/app.ts
  e2e/config/gtf/appManager.ts
  e2e/config/gtf/core.ts
  e2e/tests/app-manager/Application/properties.spec.js
  e2e/tests/app-manager/Instance/stop.spec.js
  packages/web/src/app-manager/instance.ts
  packages/web/src/app-manager/main.ts
  packages/web/src/app-manager/my.ts
Labels: tag: bug fix
