Repository Glue42/core, pull requests merged in 2020-12, with the labels that each got.

#168 Edited the React and Angular wrappers docs
  docs/core/04_core-concepts/01_web-platform/01_overview/overview.md
  docs/core/04_core-concepts/02_web-client/03_react/react.md
  docs/core/04_core-concepts/02_web-client/04_angular/angular.md
Labels: tag: documentation

#169 Add tests for all intents methods
  e2e/config/apps/coreSupport/index.js
  e2e/config/gtf/app.ts
  e2e/config/gtf/config.ts
  e2e/tests/intents/API/addIntentListener.spec.js
  e2e/tests/intents/API/all.spec.js
  e2e/tests/intents/API/find.spec.js
  e2e/tests/intents/API/raise.spec.js
  packages/web/src/intents/controller.ts
Labels: tag: bug fix

#172 Added ClientOnly mode for the platform
  packages/web-platform/platform.d.ts
  packages/web-platform/src/factory.ts
  packages/web/src/config/index.ts
  packages/web/src/web.ts
Labels: tag: enhancement

#171 Adapt @glue42/fdc3 (and fdc3-demos) for Glue42 Core v2
  docs/core/03_capabilities/99_fdc3-compliance/fdc3-compliance.md
  packages/fdc3/package-lock.json
  packages/fdc3/package.json
  packages/fdc3/src/agent.ts
  packages/fdc3/src/main.ts
  packages/fdc3/src/types/glue42FDC3DesktopAgent.d.ts
  packages/fdc3/src/types/remoteSource.d.ts
  packages/fdc3/src/types/windowtype.d.ts
  packages/fdc3/src/utils.ts
  packages/fdc3/types.d.ts
Labels: tag: new feature

#173 Edited the JS tutorial
  docs/core/04_core-concepts/01_web-platform/02_setup/setup.md
  live-examples/channels/channels-vanilla-js-ui/scripts/utils.js
  tutorials/guides/02_core/01_javascript/javascript.md
  tutorials/javascript/solution/client-details/index.html
  tutorials/javascript/solution/client-details/index.js
  tutorials/javascript/solution/client-details/lib/channelSelectorWidget.js
  tutorials/javascript/solution/client-details/lib/jquery-1.12.4.min.js
  tutorials/javascript/solution/client-details/lib/jquery-ui.min.css
  tutorials/javascript/solution/client-details/lib/jquery-ui.min.js
  tutorials/javascript/solution/clients/index.html
  tutorials/javascript/solution/clients/index.js
  tutorials/javascript/solution/clients/lib/channelSelectorWidget.js
  tutorials/javascript/solution/stocks/details/index.js
  tutorials/javascript/solution/stocks/index.html
  tutorials/javascript/solution/stocks/index.js
  tutorials/javascript/solution/stocks/lib/channelSelectorWidget.js
  tutorials/javascript/start/Clients/index.html
  tutorials/javascript/start/Clients/index.js
  tutorials/javascript/start/Clients/lib/channelSelectorWidget.js
  tutorials/javascript/start/Clients/lib/web.umd.js
  tutorials/javascript/start/Stocks/details/index.html
  tutorials/javascript/start/Stocks/details/index.js
  tutorials/javascript/start/Stocks/index.html
  tutorials/javascript/start/Stocks/index.js
  tutorials/javascript/start/Stocks/lib/channelSelectorWidget.js
  tutorials/javascript/start/Stocks/lib/platform.web.umd.js
  tutorials/javascript/start/client-details/index.html
  tutorials/javascript/start/client-details/index.js
  tutorials/javascript/start/client-details/lib/channelSelectorWidget.js
  tutorials/javascript/start/client-details/lib/jquery-1.12.4.min.js
  tutorials/javascript/start/client-details/lib/jquery-ui.min.css
  tutorials/javascript/start/client-details/lib/jquery-ui.min.js
  tutorials/javascript/start/client-details/lib/platform.web.umd.js
Labels: tag: documentation
