Repository Glue42/core, pull requests merged in 2020-11, with the labels that each got.

#152 Simplify the instance lifetime tracking
  packages/web/src/app-manager/instance.ts
  packages/web/src/app-manager/main.ts
Labels: tag: enhancement

#155 Consider the glue42gd.fdc3InitsGlue flag
  packages/fdc3/src/agent.ts
  packages/fdc3/src/channels/channels.ts
  packages/fdc3/src/index.ts
  packages/fdc3/src/main.ts
  packages/fdc3/src/types/glue42gd.d.ts
  packages/fdc3/src/types/windowtype.d.ts
  packages/fdc3/src/utils.ts
Labels: tag: bug fix, tag: enhancement

#157 Fixed broken links
  docs/core/03_capabilities/03_intents/intents.md
  docs/core/04_core-concepts/02_environment/01_overview/overview.md
  docs/core/04_core-concepts/02_environment/02_setup/setup.md
  docs/core/06_tutorials/tutorials.md
  docs/core/07_faq/faq.md
  packages/workspaces-api/workspaces.d.ts
  tutorials/guides/02_core/01_javascript/javascript.md
Labels: tag: documentation

#159 Workspaces pinned tabs
  e2e/tests/Workspaces/Frame/onWorkspaceSelected.spec.js
  packages/golden-layout/index.d.ts
  packages/golden-layout/src/js/controls/Tab.js
  packages/golden-layout/src/js/items/Stack.js
  packages/workspaces-api/src/models/frame.ts
  packages/workspaces-api/src/shared/decoders.ts
  packages/workspaces-api/src/types/subscription.ts
  packages/workspaces-api/workspaces.d.ts
  packages/workspaces-ui-core/README.md
  packages/workspaces-ui-core/package.json
  packages/workspaces-ui-core/src/componentStateMonitor.ts
  packages/workspaces-ui-core/src/config/factory.ts
  packages/workspaces-ui-core/src/export.ts
  packages/workspaces-ui-core/src/interop/types.ts
  packages/workspaces-ui-core/src/layout/controller.ts
  packages/workspaces-ui-core/src/layout/tabObserver.ts
  packages/workspaces-ui-core/src/manager.ts
  packages/workspaces-ui-core/src/store.ts
  packages/workspaces-ui-core/src/types/events.ts
  packages/workspaces-ui-core/src/types/internal.ts
  packages/workspaces-ui-core/workspaces.d.ts
  packages/workspaces-ui-react/README.md
  packages/workspaces-ui-react/src/WorkspacesElementCreationWrapper.tsx
  packages/workspaces-ui-react/src/WorkspacesWrapper.tsx
  packages/workspaces-ui-react/src/defaultComponents/WorkspaceContents.tsx
  packages/workspaces-ui-react/src/defaultComponents/popups/addApplication/AddApplicationPopup.tsx
  packages/workspaces-ui-react/src/defaultComponents/popups/addWorkspace/WorkspaceLayoutsList.tsx
  packages/workspaces-ui-react/src/defaultComponents/popups/saveWorkspace/SaveWorkspaceButton.tsx
  packages/workspaces-ui-react/src/defaultComponents/popups/saveWorkspace/SaveWorkspacePopup.tsx
  packages/workspaces-ui-react/src/index.tsx
  packages/workspaces-ui-react/src/types/internal.ts
  packages/workspaces-ui-react/src/workspacesManager.ts
  templates/workspaces-react-pinned-tabs/.env
  templates/workspaces-react-pinned-tabs/.gitignore
  templates/workspaces-react-pinned-tabs/README.md
  templates/workspaces-react-pinned-tabs/app-config/workspaces.json
  templates/workspaces-react-pinned-tabs/package-lock.json
  templates/workspaces-react-pinned-tabs/package.json
  templates/workspaces-react-pinned-tabs/public/favicon.ico
  templates/workspaces-react-pinned-tabs/public/index.html
  templates/workspaces-react-pinned-tabs/public/logo192.png
  templates/workspaces-react-pinned-tabs/public/logo512.png
  templates/workspaces-react-pinned-tabs/public/manifest.json
  templates/workspaces-react-pinned-tabs/public/robots.txt
  templates/workspaces-react-pinned-tabs/src/App.css
  templates/workspaces-react-pinned-tabs/src/App.test.tsx
  templates/workspaces-react-pinned-tabs/src/App.tsx
  templates/workspaces-react-pinned-tabs/src/CustomWorkspaceContents.tsx
  templates/workspaces-react-pinned-tabs/src/CustomWorkspaces.tsx
  templates/workspaces-react-pinned-tabs/src/index.css
  templates/workspaces-react-pinned-tabs/src/index.tsx
  templates/workspaces-react-pinned-tabs/src/logo.svg
  templates/workspaces-react-pinned-tabs/src/react-app-env.d.ts
  templates/workspaces-react-pinned-tabs/src/reportWebVitals.ts
  templates/workspaces-react-pinned-tabs/src/setupTests.ts
  templates/workspaces-react-pinned-tabs/src/workspaceDefinitions.tsx
  templates/workspaces-react-pinned-tabs/tsconfig.json
  templates/workspaces-react/README.md
  templates/workspaces-react/src/App.tsx
Labels: tag: enhancement, tag: new feature

#160 Improve ng compatibility with angular versions less than 9
  packages/ng/src/lib/glue-config.service.ts
  packages/ng/src/lib/glue-initializer.service.ts
  packages/ng/src/lib/ng.module.ts
  packages/ng/src/lib/tests/glue-config.service.spec.ts
  packages/ng/src/lib/tests/glue-initializer.service.spec.ts
  packages/ng/src/lib/tests/ng.module.spec.ts
  packages/ng/src/lib/tokens.ts
Labels: tag: bug fix

#163 Fix a race in the @glue42/fdc3 Glue42 Enterprise channel sync
  docs/core/03_capabilities/99_fdc3-compliance/fdc3-compliance.md
  packages/fdc3/src/channels/channels.ts
  packages/fdc3/src/main.ts
Labels: tag: bug fix
