Repository Glue42/core, pull requests merged in 2020-08, with the labels that each got.

#116 Add an implementation of the FDC3 Standard - the @glue42/fdc3 package
  docs/core/03_capabilities/99_fdc3-compliancy/fdc3-compliancy.md
  packages/fdc3/.editorconfig
  packages/fdc3/.gitignore
  packages/fdc3/.npmignore
  packages/fdc3/README.md
  packages/fdc3/license.md
  packages/fdc3/package-lock.json
  packages/fdc3/package.json
  packages/fdc3/rollup.config.js
  packages/fdc3/src/agent.ts
  packages/fdc3/src/channels/channel.ts
  packages/fdc3/src/channels/channels.ts
  packages/fdc3/src/index.ts
  packages/fdc3/src/main.ts
  packages/fdc3/src/utils.ts
  packages/fdc3/src/windowtype.d.ts
  packages/fdc3/tsconfig.json
  packages/fdc3/types.d.ts
  packages/web/src/app-manager/application.ts
  packages/web/src/channels/main.ts
Labels: tag: new feature

#119 Move and adapt the @glue42/web Channels API tests to e2e
  e2e/config.js
  e2e/config/glue/glue.config.json
  e2e/config/gtf.js
  e2e/index.js
  e2e/tests/channels/API/add.spec.js
  e2e/tests/channels/API/all.spec.js
  e2e/tests/channels/API/changed.spec.js
  e2e/tests/channels/API/current.spec.js
  e2e/tests/channels/API/get.spec.js
  e2e/tests/channels/API/join.spec.js
  e2e/tests/channels/API/leave.spec.js
  e2e/tests/channels/API/list.spec.js
  e2e/tests/channels/API/my.spec.js
  e2e/tests/channels/API/onChanged.spec.js
  e2e/tests/channels/API/publish.spec.js
  e2e/tests/channels/API/subscribe.spec.js
  e2e/tests/channels/API/subscribeFor.spec.js
  e2e/tests/channels/initialization.spec.js
  packages/web/tests/channels.ts
  packages/web/tests/utils.ts
Labels: tag: enhancement

#120 Improve workspaces tabs behaviour
  packages/golden-layout/src/css/glue42-dark-theme.css
  packages/golden-layout/src/css/glue42-dark-theme.css.map
  packages/golden-layout/src/css/glue42-light-theme.css
  packages/golden-layout/src/css/glue42-light-theme.css.map
  packages/golden-layout/src/css/goldenlayout-base.css
  packages/golden-layout/src/css/goldenlayout-base.css.map
  packages/golden-layout/src/js/controls/Header.js
  packages/golden-layout/src/less/goldenlayout-base.less
  packages/golden-layout/src/less/theme-specific-components-base.less
  packages/workspaces-app/assets/css/glue42-dark-theme.css
  packages/workspaces-app/assets/css/glue42-dark-theme.css.map
  packages/workspaces-app/assets/css/goldenlayout-base.css
  packages/workspaces-app/assets/css/goldenlayout-base.css.map
  packages/workspaces-app/index.html
  packages/workspaces-app/popups/index.js
  packages/workspaces-app/popups/lib/web.umd.js
  packages/workspaces-app/popups/lib/workspaces.umd.js
  packages/workspaces-app/popups/webpack.config.js
  packages/workspaces-app/popups/webpack.prod.config.js
  packages/workspaces-app/src/config/titleGenerator.ts
  packages/workspaces-app/src/layout/controller.ts
  packages/workspaces-app/src/layout/tabObserver.ts
Labels: tag: enhancement

#122 Multiple fixes and improvements in workspaces and golden-layout
  packages/golden-layout/src/css/goldenlayout-base.css
  packages/golden-layout/src/css/goldenlayout-base.css.map
  packages/golden-layout/src/js/controls/Header.js
  packages/golden-layout/src/js/items/RowOrColumn.js
  packages/golden-layout/src/less/goldenlayout-base.less
  packages/workspaces-api/src/models/frame.ts
  packages/workspaces-app/assets/css/goldenlayout-base.css
  packages/workspaces-app/assets/css/goldenlayout-base.css.map
  packages/workspaces-app/src/config/converter.ts
  packages/workspaces-app/src/config/factory.ts
  packages/workspaces-app/src/iframeController.ts
  packages/workspaces-app/src/interop/facade.ts
  packages/workspaces-app/src/layout/controller.ts
  packages/workspaces-app/src/layouts.ts
  packages/workspaces-app/src/manager.ts
Labels: tag: enhancement

#121 Edited FDC3 docs and JS Tutorial Workspaces chapter
  docs/core/03_capabilities/02_application-management/application-management.md
  docs/core/03_capabilities/99_fdc3-compliancy/fdc3-compliancy.md
  tutorials/guides/02_core/01_javascript/javascript.md
  tutorials/javascript/solution/client-details/index.js
  tutorials/javascript/solution/glue.config.dev.json
  tutorials/javascript/solution/glue.config.json
  tutorials/javascript/solution/glue.layouts.json
  tutorials/javascript/solution/stocks/details/index.js
  tutorials/javascript/solution/stocks/index.js
  tutorials/javascript/start/Clients/index.html
  tutorials/javascript/start/Clients/index.js
  tutorials/javascript/start/Stocks/details/index.js
  tutorials/javascript/start/Stocks/index.html
  tutorials/javascript/start/Stocks/index.js
  tutorials/javascript/start/client-details/index.html
  tutorials/javascript/start/client-details/index.js
Labels: tag: documentation

#124 Vulnerability fixes
  package-lock.json
  package.json
  packages/core/package-lock.json
  packages/core/package.json
  packages/core/rollup.config.js
  packages/web/package-lock.json
  packages/web/package.json
  packages/web/rollup.config.js
Labels: tag: bug fix
