Repository Glue42/core, pull requests merged in 2021-06, with the labels that each got.

#223 Fixed API descriptions and links.
  packages/core/glue.d.ts
  packages/web/web.d.ts
  packages/workspaces-api/workspaces.d.ts
Labels: tag: documentation

#224 Update desktop and deps vulnerabilities
  packages/core/changelog.md
  packages/core/package-lock.json
  packages/dev-workspaces-frame/package-lock.json
  packages/dev-workspaces-frame/package.json
  packages/fdc3/changelog.md
  packages/fdc3/package-lock.json
  packages/fdc3/package.json
  packages/golden-layout/package.json
  packages/ng/changelog.md
  packages/ng/package-lock.json
  packages/ng/package.json
  packages/react-hooks/changelog.md
  packages/react-hooks/package-lock.json
  packages/react-hooks/package.json
  packages/web-platform/changelog.md
  packages/web-platform/package-lock.json
  packages/web-platform/package.json
  packages/web/changelog.md
  packages/web/package-lock.json
  packages/web/package.json
  packages/workspaces-ui-core/changelog.md
  packages/workspaces-ui-core/package-lock.json
  packages/workspaces-ui-core/package.json
Labels: tag: internal

#225 minor doc fixes
  docs/capabilities/01_application-management/application-management.md
  docs/capabilities/04_windows/02_workspaces/03_enabling-workspaces/enabling-workspaces.md
  docs/capabilities/04_windows/02_workspaces/04_workspaces-api/workspaces-api.md
  docs/capabilities/06_notifications/01_setup/setup.md
  docs/capabilities/06_notifications/02_notifications-api/notifications-api.md
Labels: tag: documentation

#226 Fix an issue with the validation of `raiseIntent()`
  packages/fdc3/src/agent.ts
Labels: tag: bug fix
