Repository Glue42/core, pull requests merged in 2021-03, with the labels that each got.

#186 Implement Read-only Environment
  e2e/config.js
  e2e/config/gtf/index.ts
  e2e/tests/system/environment.spec.js
  packages/web-platform/platform.d.ts
  packages/web-platform/src/common/defaultConfig.ts
  packages/web-platform/src/common/types.ts
  packages/web-platform/src/controllers/main.ts
  packages/web-platform/src/controllers/system.ts
  packages/web-platform/src/platform.ts
  packages/web-platform/src/shared/decoders.ts
  packages/web-platform/src/shared/ioc.ts
  packages/web/src/config/checkSingleton.ts
  packages/web/src/shared/decoders.ts
  packages/web/src/shared/ioc.ts
  packages/web/src/shared/types.ts
  packages/web/src/system/controller.ts
  packages/web/src/system/protocol.ts
Labels: tag: new feature

#187 Implement Remote Stores For Applications
  packages/web-platform/platform.d.ts
  packages/web-platform/src/common/types.ts
  packages/web-platform/src/controllers/main.ts
  packages/web-platform/src/controllers/session.ts
  packages/web-platform/src/controllers/system.ts
  packages/web-platform/src/index.ts
  packages/web-platform/src/libs/applications/appStore/directory.ts
  packages/web-platform/src/libs/applications/appStore/remoteWatcher.ts
  packages/web-platform/src/libs/applications/controller.ts
  packages/web-platform/src/libs/applications/decoders.ts
  packages/web-platform/src/libs/applications/defaults.ts
  packages/web-platform/src/libs/applications/types.ts
  packages/web-platform/src/libs/channels/controller.ts
  packages/web-platform/src/libs/intents/controller.ts
  packages/web-platform/src/libs/layouts/controller.ts
  packages/web-platform/src/libs/windows/controller.ts
  packages/web-platform/src/libs/workspaces/controller.ts
  packages/web-platform/src/shared/decoders.ts
  packages/web-platform/src/shared/fetchTimeout.ts
  packages/web-platform/src/shared/ioc.ts
  packages/web/src/appManager/controller.ts
  packages/web/src/index.ts
  packages/web/src/shared/ioc.ts
  packages/workspaces-ui-react/README.md
Labels: tag: enhancement

#193 Workspaces refresh now correctly reuses nested references
  e2e/tests/workspaces/Parent/addWindow.spec.js
  packages/workspaces-api/src/controllers/base.ts
  packages/workspaces-api/src/controllers/main.ts
Labels: tag: bug fix

#183 Implement hibernate resume workspace
  e2e/tests/workspaces/API/onWindowRemoved.spec.js
  e2e/tests/workspaces/Workspace/close.spec.js
  e2e/tests/workspaces/Workspace/hibernate.spec.js
  e2e/tests/workspaces/Workspace/properties.spec.js
  e2e/tests/workspaces/Workspace/resume.spec.js
  packages/dev-workspaces-frame/src/App.tsx
  packages/dev-workspaces-frame/src/index.tsx
  packages/web-platform/platform.d.ts
  packages/web-platform/src/common/types.ts
  packages/web-platform/src/controllers/session.ts
  packages/web-platform/src/controllers/system.ts
  packages/web-platform/src/libs/workspaces/controller.ts
  packages/web-platform/src/libs/workspaces/decoders.ts
  packages/web-platform/src/libs/workspaces/frames.ts
  packages/web-platform/src/libs/workspaces/hibernationWatcher.ts
  packages/web-platform/src/libs/workspaces/types.ts
  packages/web-platform/src/platform.ts
  packages/web-platform/src/shared/decoders.ts
  packages/web-platform/src/shared/ioc.ts
  packages/web/src/system/controller.ts
  packages/web/src/system/protocol.ts
  packages/workspaces-api/src/communication/bridge.ts
  packages/workspaces-api/src/communication/constants.ts
  packages/workspaces-api/src/controllers/base.ts
  packages/workspaces-api/src/controllers/main.ts
  packages/workspaces-api/src/models/workspace.ts
  packages/workspaces-api/src/shared/decoders.ts
  packages/workspaces-api/src/types/controller.ts
  packages/workspaces-api/src/types/protocol.ts
  packages/workspaces-api/workspaces.d.ts
  packages/workspaces-ui-core/assets/css/goldenlayout-base.css
  packages/workspaces-ui-core/src/app/factory.ts
  packages/workspaces-ui-core/src/interop/facade.ts
  packages/workspaces-ui-core/src/interop/types.ts
  packages/workspaces-ui-core/src/layout/controller.ts
  packages/workspaces-ui-core/src/layout/stateResolver.ts
  packages/workspaces-ui-core/src/layouts.ts
  packages/workspaces-ui-core/src/manager.ts
  packages/workspaces-ui-core/src/store.ts
  packages/workspaces-ui-core/src/types/internal.ts
Labels: tag: new feature
