Repository Glue42/core, pull requests merged in 2021-01, with the labels that each got.

#158 Replace a static API InstanceWrapper property with an injected API
  packages/core/src/interop/client/client.ts
  packages/core/src/interop/client/repository.ts
  packages/core/src/interop/instance.ts
  packages/core/src/interop/interop.ts
  packages/core/tests/interop/methods.ts
Labels: tag: bug fix, tag: enhancement

#174 Change flags to be a string => any mapping (instead of string => string)
  e2e/tests/interop/API/methodAdded.spec.js
  e2e/tests/interop/API/methodRemoved.spec.js
  e2e/tests/interop/API/methods.spec.js
  e2e/tests/interop/API/servers.spec.js
  e2e/tests/interop/API/subscribe.spec.js
  e2e/tests/interop/Instance/getMethods.spec.js
  e2e/tests/interop/Instance/getStreams.spec.js
  e2e/tests/interop/MethodDefinition/properties.spec.js
  packages/core/glue.d.ts
  packages/core/src/contexts/helpers.ts
  packages/core/src/interop/client/client.ts
  packages/core/src/interop/client/repository.ts
  packages/core/src/interop/protocols/gw3/server.ts
  packages/core/src/interop/server/stream.ts
  packages/web-platform/src/libs/intents/controller.ts
  packages/web/src/intents/controller.ts
Labels: tag: enhancement

#176 Added AppManager inMemory operations
  e2e/config/gtf/config.ts
  e2e/config/gtf/index.ts
  e2e/tests/appManager/API/application.spec.js
  e2e/tests/appManager/API/applications.spec.js
  e2e/tests/appManager/API/inMemory/clear.spec.js
  e2e/tests/appManager/API/inMemory/export.spec.js
  e2e/tests/appManager/API/inMemory/import.spec.js
  e2e/tests/appManager/API/inMemory/remove.spec.js
  packages/dev-workspaces-frame/package-lock.json
  packages/dev-workspaces-frame/package.json
  packages/fdc3/package-lock.json
  packages/fdc3/package.json
  packages/fdc3/src/main.ts
  packages/ng/package-lock.json
  packages/ng/package.json
  packages/react-hooks/package-lock.json
  packages/react-hooks/package.json
  packages/web-platform/package-lock.json
  packages/web-platform/package.json
  packages/web-platform/src/controllers/main.ts
  packages/web-platform/src/factory.ts
  packages/web-platform/src/libs/applications/controller.ts
  packages/web-platform/src/libs/applications/decoders.ts
  packages/web-platform/src/libs/applications/types.ts
  packages/web-platform/src/shared/decoders.ts
  packages/web-platform/src/shared/utils.ts
  packages/web/package-lock.json
  packages/web/package.json
  packages/web/src/appManager/controller.ts
  packages/web/src/appManager/protocol.ts
  packages/web/src/layouts/controller.ts
  packages/web/src/layouts/protocol.ts
  packages/web/src/shared/decoders.ts
  packages/web/web.d.ts
  packages/workspaces-ui-core/package-lock.json
  packages/workspaces-ui-core/package.json
Labels: tag: enhancement

#177 Added Angular tutorial V2 And Start of Day Demo Updated To V2
  demos/start-of-day/build.js
  demos/start-of-day/glue.config.dev.json
  demos/start-of-day/glue.config.json
  demos/start-of-day/glue.layouts.json
  demos/start-of-day/package-lock.json
  demos/start-of-day/package.json
  demos/start-of-day/projects/clients/src/app/app.module.ts
  demos/start-of-day/projects/news/src/app/app.module.ts
  demos/start-of-day/projects/portfolio/src/app/app.component.ts
  demos/start-of-day/projects/portfolio/src/app/app.module.ts
  demos/start-of-day/projects/transactions/src/app/app.module.ts
  demos/start-of-day/projects/welcome/src/app/app.component.ts
  demos/start-of-day/projects/welcome/src/app/app.module.ts
  demos/start-of-day/shared/data/glue.service.ts
  demos/start-of-day/workspaces/asset-manifest.json
  demos/start-of-day/workspaces/favicon.ico
  demos/start-of-day/workspaces/index.html
  demos/start-of-day/workspaces/logo192.png
  demos/start-of-day/workspaces/logo512.png
  demos/start-of-day/workspaces/manifest.json
  demos/start-of-day/workspaces/robots.txt
  demos/start-of-day/workspaces/static/css/main.c73e9fa3.chunk.css
  demos/start-of-day/workspaces/static/css/main.c73e9fa3.chunk.css.map
  demos/start-of-day/workspaces/static/js/2.f21f54c2.chunk.js
  demos/start-of-day/workspaces/static/js/2.f21f54c2.chunk.js.LICENSE.txt
  demos/start-of-day/workspaces/static/js/2.f21f54c2.chunk.js.map
  demos/start-of-day/workspaces/static/js/3.6513b2a9.chunk.js
  demos/start-of-day/workspaces/static/js/3.6513b2a9.chunk.js.map
  demos/start-of-day/workspaces/static/js/main.45afbf7d.chunk.js
  demos/start-of-day/workspaces/static/js/main.45afbf7d.chunk.js.LICENSE.txt
  demos/start-of-day/workspaces/static/js/main.45afbf7d.chunk.js.map
  demos/start-of-day/workspaces/static/js/runtime-main.e05b5a16.js
  demos/start-of-day/workspaces/static/js/runtime-main.e05b5a16.js.map
  docs/core/03_capabilities/02_application-management/application-management.md
  packages/web-platform/src/common/types.ts
  packages/web-platform/src/libs/applications/controller.ts
  packages/web-platform/src/libs/applications/decoders.ts
  packages/web-platform/src/platform.ts
  packages/web/src/appManager/controller.ts
  packages/web/src/appManager/protocol.ts
  packages/web/src/config/index.ts
  packages/web/src/shared/decoders.ts
  packages/workspaces-ui-core/src/layout/stateResolver.ts
  packages/workspaces-ui-core/src/manager.ts
  tutorials/angular/solution/clients/angular.json
  tutorials/angular/solution/clients/package-lock.json
  tutorials/angular/solution/clients/package.json
  tutorials/angular/solution/clients/src/app/app.component.ts
  tutorials/angular/solution/clients/src/app/app.module.ts
  tutorials/angular/solution/clients/src/app/glue.service.ts
  tutorials/angular/solution/package-lock.json
  tutorials/angular/solution/package.json
  tutorials/angular/solution/stocks/angular.json
  tutorials/angular/solution/stocks/package-lock.json
  tutorials/angular/solution/stocks/package.json
  tutorials/angular/solution/stocks/src/app/app.module.ts
  tutorials/angular/solution/stocks/src/app/glue.service.ts
  tutorials/guides/02_core/03_angular/angular.md
  tutorials/guides/02_core/03_angular/config.json
Labels: tag: documentation
