Repository Glue42/core, pull requests merged in 2021-02, with the labels that each got.

#181 Fixes issue with restoring workspace windows titles
  e2e/config/gtf/config.ts
  e2e/tests/workspaces/API/layouts/export.spec.js
  e2e/tests/workspaces/API/layouts/import.spec.js
  e2e/tests/workspaces/WorkspaceWindow/properties.spec.js
  packages/web-platform/src/libs/workspaces/decoders.ts
  packages/web-platform/src/shared/decoders.ts
  packages/web/src/shared/decoders.ts
  packages/workspaces-ui-core/src/manager.ts
Labels: tag: bug fix

#182 Correctly set workspace app titles
  e2e/tests/workspaces/API/layouts/onRemoved.spec.js
  e2e/tests/workspaces/API/layouts/onSaved.spec.js
  e2e/tests/workspaces/WorkspaceWindow/properties.spec.js
  packages/web/src/layouts/controller.ts
  packages/workspaces-ui-core/src/manager.ts
Labels: tag: bug fix

#180 Nest the intent metadata inside a intent property of the method flags
  packages/fdc3/src/channels/channels.ts
  packages/web-platform/src/libs/intents/controller.ts
  packages/web/src/intents/controller.ts
Labels: tag: internal

#185 Enable platform frames
  packages/core/src/connection/transports/webPlatform.ts
  packages/dev-workspaces-frame/package.json
  packages/dev-workspaces-frame/src/index.tsx
  packages/web-platform/platform.d.ts
  packages/web-platform/src/common/defaultConfig.ts
  packages/web-platform/src/controllers/glue.ts
  packages/web-platform/src/controllers/main.ts
  packages/web-platform/src/controllers/session.ts
  packages/web-platform/src/factory.ts
  packages/web-platform/src/fallbacks/core.ts
  packages/web-platform/src/fallbacks/enterprise.ts
  packages/web-platform/src/libs/workspaces/frames.ts
  packages/web-platform/src/libs/workspaces/types.ts
  packages/web-platform/src/platform.ts
  packages/web-platform/src/shared/decoders.ts
  packages/workspaces-ui-core/src/iframeController.ts
  packages/workspaces-ui-core/src/manager.ts
Labels: tag: enhancement
