Repository Glue42/core, pull requests merged in 2021-11, with the labels that each got.

#256 Updated the react dependencies
  packages/react-hooks/changelog.md
  packages/react-hooks/package.json
  packages/workspaces-ui-react/changelog.md
  packages/workspaces-ui-react/package.json
Labels: tag: enhancement

#257 Implemented waitForFrame
  e2e/tests/workspaces/API/waitForFrame.spec.js
  packages/workspaces-api/changelog.md
  packages/workspaces-api/src/main.ts
  packages/workspaces-api/workspaces.d.ts
Labels: tag: new feature

#260 Empty placeholder improvements
  e2e/tests/workspaces/Parent/addColumn.spec.js
  e2e/tests/workspaces/Parent/addGroup.spec.js
  e2e/tests/workspaces/Parent/addRow.spec.js
  e2e/tests/workspaces/Parent/addWindow.spec.js
  e2e/tests/workspaces/Parent/close.spec.js
  e2e/tests/workspaces/Parent/removeChild.spec.js
  e2e/tests/workspaces/Workspace/addColumn.spec.js
  e2e/tests/workspaces/Workspace/addGroup.spec.js
  e2e/tests/workspaces/Workspace/addRow.spec.js
  packages/golden-layout/changelog.md
  packages/golden-layout/src/js/items/RowOrColumn.js
  packages/workspaces-ui-core/changelog.md
  packages/workspaces-ui-core/src/config/factory.ts
  packages/workspaces-ui-core/src/layout/controller.ts
  packages/workspaces-ui-core/src/manager.ts
Labels: tag: enhancement

#266 Improve core electron detection
  packages/core/changelog.md
  packages/core/glue.d.ts
  packages/core/src/config.ts
  packages/core/src/index.ts
  packages/core/src/interop/instance.ts
  packages/core/tests/core/base.ts
  packages/core/tests/core/core.ts
Labels: tag: enhancement

#267 Update all packages to @glue42/desktop 5.7.6
  packages/dev-workspaces-frame/package-lock.json
  packages/dev-workspaces-frame/package.json
  packages/fdc3/package-lock.json
  packages/fdc3/package.json
  packages/ng/package-lock.json
  packages/ng/package.json
  packages/react-hooks/package-lock.json
  packages/react-hooks/package.json
  packages/web-platform/package-lock.json
  packages/web-platform/package.json
  packages/web/package-lock.json
  packages/web/package.json
  packages/workspaces-ui-core/package-lock.json
  packages/workspaces-ui-core/package.json
Labels: tag: internal
