Repository Glue42/core, pull requests merged in 2021-05, with the labels that each got.

#206 added empty object as default value
  e2e/tests/workspaces/Workspace/saveLayout.spec.js
  packages/workspaces-ui-core/src/layouts.ts
Labels: tag: bug fix

#204 bugfix: js-tutorial
  tutorials/javascript/start/Clients/index.html
Labels: tag: bug fix, tag: documentation

#215 docs: update creation of channel selector widget
  tutorials/guides/02_core/01_javascript/javascript.md
Labels: tag: documentation

#214 reconfigure js tutorial server to prevent caching
  tutorials/javascript/start/package.json
Labels: dependencies

#216 Bugfix/invalid boxes size in workspaces
  e2e/tests/workspaces/API/createWorkspace.spec.js
  e2e/tests/workspaces/Parent/properties.spec.js
  e2e/tests/workspaces/WorkspaceWindow/properties.spec.js
  packages/golden-layout/changelog.md
  packages/golden-layout/src/js/items/RowOrColumn.js
  packages/web-platform/changelog.md
  packages/web-platform/src/libs/workspaces/decoders.ts
  packages/workspaces-api/changelog.md
  packages/workspaces-api/src/shared/decoders.ts
  packages/workspaces-ui-core/changelog.md
  packages/workspaces-ui-core/src/layout/controller.ts
  packages/workspaces-ui-core/src/manager.ts
  packages/workspaces-ui-core/src/state/containerWrapper.ts
  packages/workspaces-ui-core/src/state/resolver.ts
  packages/workspaces-ui-core/src/state/windowWrapper.ts
  packages/workspaces-ui-core/src/state/workspaceWrapper.ts
Labels: tag: bug fix

#219 Implement Advanced Notifications
  e2e/config.js
  e2e/config/gtf/index.ts
  e2e/tests/notifications/raise.spec.js
  package-lock.json
  package.json
  packages/web-platform/changelog.md
  packages/web-platform/platform.d.ts
  packages/web-platform/src/common/constants.ts
  packages/web-platform/src/common/types.ts
  packages/web-platform/src/controllers/main.ts
  packages/web-platform/src/controllers/serviceWorker.ts
  packages/web-platform/src/controllers/state.ts
  packages/web-platform/src/libs/applications/controller.ts
  packages/web-platform/src/libs/notifications/controller.ts
  packages/web-platform/src/libs/notifications/decoders.ts
  packages/web-platform/src/libs/notifications/types.ts
  packages/web-platform/src/libs/windows/controller.ts
  packages/web-platform/src/libs/workspaces/controller.ts
  packages/web-platform/src/platform.ts
  packages/web-platform/src/shared/decoders.ts
  packages/web-platform/src/shared/ioc.ts
  packages/web-worker/changelog.md
  packages/web-worker/package-lock.json
  packages/web-worker/package.json
  packages/web-worker/rollup.config.js
  packages/web-worker/src/constants.ts
  packages/web-worker/src/decoders.ts
  packages/web-worker/src/index.ts
  packages/web-worker/src/worker.ts
  packages/web-worker/web.worker.d.ts
  packages/web/changelog.md
  packages/web/src/appManager/controller.ts
  packages/web/src/config/index.ts
  packages/web/src/notifications/controller.ts
  packages/web/src/notifications/notification.ts
  packages/web/src/notifications/protocol.ts
  packages/web/src/shared/decoders.ts
  packages/web/src/shared/ioc.ts
  packages/web/src/shared/types.ts
  packages/web/src/web.ts
  packages/web/web.d.ts
Labels: tag: new feature
