Repository Glue42/core, pull requests merged in 2022-05, with the labels that each got.

#379 Edited Connecting to Glue42 Enterprise.
  docs/developers/01_core-concepts/01_web-platform/02_setup/setup.md
  docs/glue42-enterprise/02_connecting/connecting.md
  docs/glue42-enterprise/02_connection/config.json
  docs/glue42-enterprise/02_connection/connection.md
Labels: tag: documentation

#378 Resolve Dependency Vulnerabilities
  .gitignore
  e2e/config/apps/puppet/glue-commands.js
  e2e/config/apps/puppet/index.js
  e2e/config/gtf/contexts.ts
  e2e/config/gtf/gtf.d.ts
  e2e/config/gtf/puppet/clients/base-client.ts
  e2e/config/gtf/puppet/clients/glue-core-client.ts
  e2e/config/gtf/puppet/clients/glue-web-client.ts
  e2e/config/gtf/puppet/clients/web-platform.ts
  e2e/config/gtf/puppet/common/types.ts
  e2e/config/gtf/puppet/index.ts
  e2e/tests/connection/connected.spec.js
  e2e/tests/connection/contexts.spec.js
  e2e/tests/connection/disconnected.spec.js
  e2e/tests/connection/interop.spec.js
  gulpfile.js
  package-lock.json
  package.json
  packages/core/package-lock.json
  packages/core/package.json
  packages/core/src/interop/protocols/gw3/client-streaming.ts
  packages/core/src/interop/protocols/gw3/client.ts
  packages/core/src/interop/protocols/gw3/factory.ts
  packages/core/src/utils/timed-cache.ts
  packages/golden-layout/package-lock.json
  packages/golden-layout/package.json
  packages/ng/package-lock.json
  packages/ng/package.json
  packages/react-hooks/package-lock.json
  packages/react-hooks/package.json
  packages/web-platform/package.json
  packages/web-platform/src/controllers/glue.ts
  packages/web-platform/src/controllers/main.ts
  packages/web-platform/src/libs/workspaces/controller.ts
  packages/web-platform/src/platform.ts
  packages/web-worker/package-lock.json
  packages/web/package-lock.json
  packages/web/package.json
  packages/web/tests/initializer.ts
  packages/workspaces-ui-core/package-lock.json
  packages/workspaces-ui-core/package.json
  packages/workspaces-ui-react/package-lock.json
  packages/workspaces-ui-react/package.json
  tsconfig.json
Labels: tag: internal

#381 Fix a breaking change introduced by the multiple transports PR
  packages/web-platform/changelog.md
  packages/web-platform/package-lock.json
  packages/web-platform/package.json
  packages/web-platform/src/common/constants.ts
  packages/web-platform/src/common/defaultConfig.ts
  packages/web-platform/src/common/types.ts
  packages/web-platform/src/connection/portsBridge.ts
  packages/web-platform/src/controllers/glue.ts
  packages/web-platform/src/controllers/system.ts
  packages/web-platform/src/platform.ts
  packages/web-platform/src/shared/ioc.ts
  packages/web/changelog.md
  packages/web/package-lock.json
  packages/web/package.json
  packages/web/src/communication/bridge.ts
  packages/web/src/config/index.ts
  packages/web/src/enterprise/index.ts
  packages/web/src/shared/ioc.ts
  packages/web/src/shared/session.ts
  packages/web/src/shared/types.ts
  packages/web/src/web.ts
  packages/workspaces-api/changelog.md
  packages/workspaces-api/src/communication/interop-transport.ts
  packages/workspaces-ui-core/changelog.md
  packages/workspaces-ui-core/src/app/factory.ts
  packages/workspaces-ui-core/src/config/system.ts
  packages/workspaces-ui-core/src/interop/facade.ts
Labels: tag: bug fix
