Repository Glue42/core, pull requests merged in 2022-06, with the labels that each got.

#383 Multiple context listeners before joining a channel inside of @glue42/fdc3
  packages/fdc3/package-lock.json
  packages/fdc3/package.json
  packages/fdc3/src/channels/channels.ts
Labels: tag: bug fix

#384 fixed links, minor doc edits
  docs/capabilities/01_application-management/application-management.md
  docs/capabilities/04_windows/02_workspaces/02_workspaces-app/workspaces-app.md
  docs/getting-started/04_fdc3-compliance/fdc3-compliance.md
  docs/glue42-enterprise/02_connection/connection.md
  tutorials/guides/01_javascript/javascript.md
Labels: tag: documentation

#417 The Auth object now accepts a provider context in addition to provider.
  packages/core/glue.d.ts
  packages/core/src/connection/protocols/gw3.ts
  packages/web-platform/src/connection/preferred.ts
  packages/web-platform/src/shared/decoders.ts
Labels: tag: new feature

#420 Enabled addWindow and addContainer and added tests
  e2e/tests/workspaces/Parent/addColumn.spec.js
  e2e/tests/workspaces/Parent/addGroup.spec.js
  e2e/tests/workspaces/Parent/addRow.spec.js
  e2e/tests/workspaces/Parent/addWindow.spec.js
  e2e/tests/workspaces/Workspace/addColumn.spec.js
  e2e/tests/workspaces/Workspace/addGroup.spec.js
  e2e/tests/workspaces/Workspace/addRow.spec.js
  e2e/tests/workspaces/Workspace/addWindow.spec.js
  packages/golden-layout/changelog.md
  packages/golden-layout/src/js/items/AbstractContentItem.js
  packages/workspaces-ui-core/changelog.md
  packages/workspaces-ui-core/src/layout/controller.ts
  packages/workspaces-ui-core/src/manager.ts
Labels: tag: new feature

#423 Add a maximize boundary in workspaces
  packages/golden-layout/changelog.md
  packages/golden-layout/index.d.ts
  packages/golden-layout/src/js/LayoutManager.js
  packages/golden-layout/src/js/items/RowOrColumn.js
  packages/workspaces-api/changelog.md
  packages/workspaces-api/src/models/base/base.ts
  packages/workspaces-api/src/models/column.ts
  packages/workspaces-api/src/models/row.ts
  packages/workspaces-api/src/shared/decoders.ts
  packages/workspaces-api/src/types/protocol.ts
  packages/workspaces-api/workspaces.d.ts
  packages/workspaces-ui-core/src/layout/controller.ts
  packages/workspaces-ui-core/src/types/internal.ts
Labels: tag: new feature

#428 Fix when all callbacks are invoked with the same shortcuts no matter where they are registered
  packages/workspaces-api/src/communication/constants.ts
  packages/workspaces-api/src/controllers/shortcuts.ts
  packages/workspaces-api/src/shared/decoders.ts
  packages/workspaces-api/src/types/protocol.ts
Labels: tag: bug fix
