Repository Glue42/core, pull requests merged in 2022-09, with the labels that each got.

#485 Clients embedded in iframes now always have unique ids
  packages/core/changelog.md
  packages/core/src/connection/transports/webPlatform.ts
Labels: tag: bug fix

#487 Add set maximization boundary
  e2e/tests/workspaces/Parent/setMaximizationBoundary.spec.js
  packages/golden-layout/changelog.md
  packages/golden-layout/src/js/utils/TabDragListener.js
  packages/web-platform/changelog.md
  packages/web-platform/src/libs/workspaces/controller.ts
  packages/web-platform/src/libs/workspaces/decoders.ts
  packages/web-platform/src/libs/workspaces/types.ts
  packages/workspaces-api/changelog.md
  packages/workspaces-api/src/communication/constants.ts
  packages/workspaces-api/src/controllers/base.ts
  packages/workspaces-api/src/controllers/main.ts
  packages/workspaces-api/src/models/base/base.ts
  packages/workspaces-api/src/models/column.ts
  packages/workspaces-api/src/models/row.ts
  packages/workspaces-api/src/shared/decoders.ts
  packages/workspaces-api/src/types/controller.ts
  packages/workspaces-api/src/types/protocol.ts
  packages/workspaces-api/temp.ts
  packages/workspaces-ui-core/changelog.md
  packages/workspaces-ui-core/src/interop/facade.ts
  packages/workspaces-ui-core/src/interop/types.ts
  packages/workspaces-ui-core/src/manager.ts
  packages/workspaces-ui-core/src/state/containerWrapper.ts
Labels: tag: bug fix, tag: new feature

#496 The platform now adds a g42 prefix to all windows opened by it
  e2e/tests/appManager/Application/start.spec.js
  e2e/tests/windows/API/open.spec.js
  e2e/tests/workspaces/API/onWindowAdded.spec.js
  e2e/tests/workspaces/API/onWindowLoaded.spec.js
  e2e/tests/workspaces/Frame/onWindowLoaded.spec.js
  e2e/tests/workspaces/Workspace/onWindowLoaded.spec.js
  e2e/tests/workspaces/WorkspaceWindow/getGdWindow.spec.js
  e2e/tests/workspaces/WorkspaceWindow/properties.spec.js
  packages/web-platform/src/libs/applications/controller.ts
  packages/web-platform/src/libs/windows/controller.ts
  packages/workspaces-ui-core/src/app/factory.ts
  packages/workspaces-ui-core/src/iframeController.ts
  packages/workspaces-ui-core/src/layouts.ts
  packages/workspaces-ui-core/src/utils/index.ts
Labels: tag: enhancement, tag: new feature

#500 Prepare Web Platform For Core+
  packages/web-platform/platform.d.ts
  packages/web-platform/src/controllers/main.ts
  packages/web-platform/src/factory.ts
  packages/web-platform/src/platform.ts
  packages/web-platform/src/shared/decoders.ts
  packages/web/src/shared/decoders.ts
Labels: tag: new feature
