Repository Glue42/core, pull requests merged in 2022-11, with the labels that each got.

#527 Extend Web Platform with Core+ support
  packages/web-platform/changelog.md
  packages/web-platform/package-lock.json
  packages/web-platform/package.json
  packages/web-platform/platform.d.ts
  packages/web-platform/rollup.config.no.gateway.js
  packages/web-platform/src/common/types.ts
  packages/web-platform/src/connection/no-gateway.ts
  packages/web-platform/src/controllers/domains.ts
  packages/web-platform/src/controllers/main.ts
  packages/web-platform/src/controllers/plugins.ts
  packages/web-platform/src/libs/workspaces/controller.ts
  packages/web-platform/src/platform.ts
  packages/web-platform/src/shared/decoders.ts
  packages/web-platform/src/shared/ioc.ts
Labels: tag: new feature

#528 Fixes various types issues in web platform
  packages/web-platform/platform.d.ts
  packages/web-platform/src/connection/preferred.ts
  packages/web-platform/src/controllers/main.ts
  packages/web-platform/src/controllers/serviceWorker.ts
  packages/web-platform/src/libs/layouts/idbStore.ts
  packages/web-platform/src/libs/notifications/controller.ts
  packages/web-platform/src/libs/workspaces/hibernationWatcher.ts
  packages/web-platform/src/shared/decoders.ts
  packages/web-platform/src/shared/ioc.ts
  packages/web-platform/src/shared/promisePlus.ts
Labels: tag: enhancement

#526 Create intents resolver api
  packages/intents-resolver-api/.editorconfig
  packages/intents-resolver-api/.gitignore
  packages/intents-resolver-api/.npmignore
  packages/intents-resolver-api/README.md
  packages/intents-resolver-api/changelog.md
  packages/intents-resolver-api/intents-resolver.d.ts
  packages/intents-resolver-api/license.md
  packages/intents-resolver-api/package-lock.json
  packages/intents-resolver-api/package.json
  packages/intents-resolver-api/rollup.config.js
  packages/intents-resolver-api/src/controllers/glue.ts
  packages/intents-resolver-api/src/controllers/main.ts
  packages/intents-resolver-api/src/index.ts
  packages/intents-resolver-api/src/shared/constants.ts
  packages/intents-resolver-api/src/shared/decoders.ts
  packages/intents-resolver-api/src/shared/ioc.ts
  packages/intents-resolver-api/src/shared/utils.ts
  packages/intents-resolver-api/src/types/glue.ts
  packages/intents-resolver-api/src/types/types.ts
  packages/intents-resolver-api/tsconfig.json
  packages/web/changelog.md
  packages/web/src/appManager/controller.ts
  packages/web/src/intents/constants.ts
  packages/web/src/intents/controller.ts
  packages/web/src/intents/protocol.ts
  packages/web/src/shared/decoders.ts
  packages/web/src/shared/types.ts
  packages/web/web.d.ts
  templates/intents-resolver/.env
  templates/intents-resolver/.gitignore
  templates/intents-resolver/README.md
  templates/intents-resolver/package-lock.json
  templates/intents-resolver/package.json
  templates/intents-resolver/public/favicon.ico
  templates/intents-resolver/public/index.html
  templates/intents-resolver/public/logo192.png
  templates/intents-resolver/public/logo512.png
  templates/intents-resolver/public/manifest.json
  templates/intents-resolver/public/robots.txt
  templates/intents-resolver/src/App.js
  templates/intents-resolver/src/App.test.js
  templates/intents-resolver/src/index.css
  templates/intents-resolver/src/index.js
  templates/intents-resolver/src/lib/desktop.es.js
  templates/intents-resolver/src/lib/desktop.es.js.map
  templates/intents-resolver/src/lib/intents-resolver-api.es.js
  templates/intents-resolver/src/lib/platform.web.es.js
  templates/intents-resolver/src/lib/web.es.js
  templates/intents-resolver/src/logo.svg
  templates/intents-resolver/src/reportWebVitals.js
  templates/intents-resolver/src/setupTests.js
Labels: tag: new feature

#544 Minor intents API fixes
  packages/web-platform/src/libs/workspaces/controller.ts
  packages/web-platform/src/libs/workspaces/decoders.ts
  packages/web-platform/src/libs/workspaces/types.ts
  packages/web/src/intents/controller.ts
  packages/web/src/shared/decoders.ts
  packages/web/src/shared/systemOperations.ts
  packages/web/src/shared/types.ts
  templates/intents-resolver/public/core-plus-symbol.svg
  templates/intents-resolver/public/favicon.ico
  templates/intents-resolver/public/index.html
  templates/intents-resolver/public/logo192.png
  templates/intents-resolver/public/logo512.png
  templates/intents-resolver/public/manifest.json
  templates/intents-resolver/src/index.js
Labels: tag: bug fix

#546 Replace subscription for onInstanceStarted with serverMethodAdded
  packages/intents-resolver-api/src/controllers/glue.ts
  packages/intents-resolver-api/src/controllers/main.ts
  packages/intents-resolver-api/src/shared/constants.ts
  packages/intents-resolver-api/src/shared/decoders.ts
  packages/intents-resolver-api/src/types/glue.ts
  packages/intents-resolver-api/src/types/types.ts
  packages/web/web.d.ts
Labels: tag: enhancement

#560 Minor dev environment fixes
  packages/core/package-lock.json
  packages/core/package.json
  packages/core/rollup.config.js
  packages/fdc3/package-lock.json
  packages/fdc3/package.json
  packages/fdc3/rollup.config.js
  packages/intents-resolver-api/package-lock.json
  packages/intents-resolver-api/package.json
  packages/intents-resolver-api/rollup.config.js
  packages/web-platform/package-lock.json
  packages/web-platform/package.json
  packages/web-platform/rollup.config.js
  packages/web-worker/package-lock.json
  packages/web-worker/package.json
  packages/web-worker/rollup.config.js
  packages/web/.npmignore
  packages/web/package-lock.json
  packages/web/package.json
  packages/web/rollup.config.js
  packages/workspaces-api/package-lock.json
  packages/workspaces-api/package.json
  packages/workspaces-api/rollup.config.js
  packages/workspaces-ui-core/package-lock.json
  packages/workspaces-ui-core/package.json
  packages/workspaces-ui-core/rollup.config.js
  packages/workspaces-ui-react/package-lock.json
  packages/workspaces-ui-react/package.json
  packages/workspaces-ui-react/rollup.config.js
Labels: tag: bug fix, tag: enhancement

#565 Fix Web initiation fail when more than 50 clients are connected
  packages/web-platform/package-lock.json
  packages/web-platform/package.json
  packages/web-platform/platform.d.ts
  packages/web-platform/src/connection/gateway.ts
  packages/web-platform/src/controllers/glue.ts
  packages/web-platform/src/libs/applications/controller.ts
  packages/web-platform/src/libs/windows/controller.ts
  packages/web-platform/src/libs/workspaces/controller.ts
  packages/web-platform/src/shared/decoders.ts
Labels: tag: bug fix
