Repository Glue42/core, pull requests merged in 2022-08, with the labels that each got.

#472 Core docs style edits and updates.
  docs/capabilities/02_intents/intents.md
  docs/capabilities/04_windows/01_window-management/window-management.md
  docs/capabilities/04_windows/02_workspaces/01_overview/overview.md
  docs/capabilities/04_windows/02_workspaces/02_workspaces-app/workspaces-app.md
  docs/capabilities/04_windows/02_workspaces/03_enabling-workspaces/enabling-workspaces.md
  docs/capabilities/04_windows/02_workspaces/04_workspaces-api/workspaces-api.md
  docs/capabilities/04_windows/03_layouts/01_setup/setup.md
  docs/capabilities/06_notifications/01_setup/setup.md
  docs/capabilities/06_notifications/02_notifications-api/notifications-api.md
  docs/developers/01_core-concepts/01_web-platform/02_setup/setup.md
  docs/developers/01_core-concepts/02_web-client/02_javascript/javascript.md
  docs/developers/01_core-concepts/02_web-client/03_react/react.md
  docs/developers/01_core-concepts/02_web-client/04_angular/angular.md
  docs/getting-started/03_quick-start/quick-start.md
  docs/getting-started/05_fdc3-compliance/fdc3-compliance.md
  docs/getting-started/06_faq/faq.md
  packages/web/web.d.ts
Labels: tag: documentation

#482 Fix bug with data wrapping when broadcasting a context
  packages/fdc3/changelog.md
  packages/fdc3/src/channels/channel.ts
  packages/fdc3/src/utils.ts
Labels: tag: bug fix

#473 Add allow reorder option
  e2e/tests/workspaces/API/createWorkspace.spec.js
  e2e/tests/workspaces/API/getMyFrame.spec.js
  e2e/tests/workspaces/API/getMyWorkspace.spec.js
  e2e/tests/workspaces/API/inWorkspace.spec.js
  e2e/tests/workspaces/API/restoreWorkspace.spec.js
  e2e/tests/workspaces/Frame/init.spec.js
  e2e/tests/workspaces/Parent/addGroup.spec.js
  e2e/tests/workspaces/Parent/addWindow.spec.js
  e2e/tests/workspaces/Parent/lock.spec.js
  e2e/tests/workspaces/Workspace/addGroup.spec.js
  e2e/tests/workspaces/Workspace/lock.spec.js
  e2e/tests/workspaces/Workspace/resume.spec.js
  e2e/tests/workspaces/WorkspaceWindow/lock.spec.js
  packages/golden-layout/changelog.md
  packages/golden-layout/index.d.ts
  packages/golden-layout/src/js/controls/Tab.js
  packages/web-platform/changelog.md
  packages/web-platform/src/libs/workspaces/decoders.ts
  packages/web-platform/src/libs/workspaces/types.ts
  packages/web-platform/src/shared/decoders.ts
  packages/web/src/shared/decoders.ts
  packages/workspaces-api/changelog.md
  packages/workspaces-api/src/models/base/base.ts
  packages/workspaces-api/src/models/group.ts
  packages/workspaces-api/src/models/window.ts
  packages/workspaces-api/src/models/workspace.ts
  packages/workspaces-api/src/shared/decoders.ts
  packages/workspaces-api/src/types/protocol.ts
  packages/workspaces-api/workspaces.d.ts
  packages/workspaces-ui-core/changelog.md
  packages/workspaces-ui-core/src/config/converter.ts
  packages/workspaces-ui-core/src/config/factory.ts
  packages/workspaces-ui-core/src/interop/facade.ts
  packages/workspaces-ui-core/src/interop/types.ts
  packages/workspaces-ui-core/src/layout/controller.ts
  packages/workspaces-ui-core/src/locking.ts
  packages/workspaces-ui-core/src/manager.ts
  packages/workspaces-ui-core/src/state/containerWrapper.ts
  packages/workspaces-ui-core/src/state/windowWrapper.ts
  packages/workspaces-ui-core/src/state/workspaceWrapper.ts
  packages/workspaces-ui-core/src/types/internal.ts
  packages/workspaces-ui-core/test/config/converter/convertToAPIConfig.spec.ts
  packages/workspaces-ui-core/test/config/converter/convertToRendererConfig.spec.ts
  packages/workspaces-ui-core/test/config/factory/createApiWindow.spec.ts
  packages/workspaces-ui-core/test/config/factory/createGDWindowConfig.spec.ts
Labels: tag: new feature
