Repository Glue42/core, pull requests merged in 2022-10, with the labels that each got.

#501 Improve plugins platform controls
  packages/web-platform/platform.d.ts
  packages/web-platform/src/common/types.ts
  packages/web-platform/src/controllers/glue.ts
  packages/web-platform/src/controllers/main.ts
  packages/web-platform/src/controllers/plugins.ts
  packages/web-platform/src/shared/decoders.ts
  packages/web-platform/src/shared/ioc.ts
  packages/workspaces-api/changelog.md
  packages/workspaces-api/src/main.ts
  packages/workspaces-api/workspaces.d.ts
Labels: tag: enhancement

#508 Started searching for the glue object in the react context
  packages/dev-workspaces-frame/package-lock.json
  packages/dev-workspaces-frame/package.json
  packages/dev-workspaces-frame/src/App.tsx
  packages/dev-workspaces-frame/src/index.tsx
  packages/workspaces-api/changelog.md
  packages/workspaces-api/src/models/frame.ts
  packages/workspaces-ui-react/changelog.md
  packages/workspaces-ui-react/package-lock.json
  packages/workspaces-ui-react/src/defaultComponents/workspace/tabV2/LockOptions.tsx
  packages/workspaces-ui-react/src/defaultComponents/workspace/tabV2/WorkspaceTabV2.tsx
Labels: tag: bug fix

#507 Added the missing export for WorkspaceTabV2
  packages/workspaces-ui-react/src/index.tsx
Labels: tag: bug fix

#512 Extend the control protocol with commands detection
  packages/web-platform/src/common/types.ts
  packages/web-platform/src/connection/gateway.ts
  packages/web-platform/src/connection/portsBridge.ts
  packages/web-platform/src/controllers/system.ts
  packages/web-platform/src/libs/applications/controller.ts
  packages/web-platform/src/libs/applications/decoders.ts
  packages/web-platform/src/libs/applications/types.ts
  packages/web-platform/src/libs/channels/controller.ts
  packages/web-platform/src/libs/channels/decoders.ts
  packages/web-platform/src/libs/extension/controller.ts
  packages/web-platform/src/libs/extension/decoders.ts
  packages/web-platform/src/libs/extension/types.ts
  packages/web-platform/src/libs/intents/controller.ts
  packages/web-platform/src/libs/intents/decoders.ts
  packages/web-platform/src/libs/intents/types.ts
  packages/web-platform/src/libs/layouts/controller.ts
  packages/web-platform/src/libs/layouts/decoders.ts
  packages/web-platform/src/libs/layouts/types.ts
  packages/web-platform/src/libs/notifications/controller.ts
  packages/web-platform/src/libs/notifications/decoders.ts
  packages/web-platform/src/libs/notifications/types.ts
  packages/web-platform/src/libs/windows/controller.ts
  packages/web-platform/src/libs/windows/decoders.ts
  packages/web-platform/src/libs/windows/types.ts
  packages/web-platform/src/libs/workspaces/controller.ts
  packages/web-platform/src/libs/workspaces/decoders.ts
  packages/web-platform/src/libs/workspaces/types.ts
  packages/web-platform/src/shared/decoders.ts
  packages/workspaces-ui-core/package-lock.json
  packages/workspaces-ui-core/package.json
  packages/workspaces-ui-core/src/iframeController.ts
  packages/workspaces-ui-core/src/interop/facade.ts
  packages/workspaces-ui-core/src/interop/platformCommunicator.ts
  packages/workspaces-ui-core/src/interop/types.ts
  packages/workspaces-ui-core/src/manager.ts
  packages/workspaces-ui-core/src/utils/index.ts
Labels: tag: enhancement

#515 Enabled bulk imports of up to 999 layouts
  e2e/tests/workspaces/API/layouts/import.spec.js
  packages/web-platform/src/libs/layouts/controller.ts
  packages/web/src/layouts/controller.ts
  packages/workspaces-api/src/controllers/base.ts
  packages/workspaces-api/src/controllers/main.ts
  packages/workspaces-api/src/main.ts
  packages/workspaces-api/src/types/controller.ts
  packages/workspaces-api/src/types/glue.ts
Labels: tag: bug fix

#519 Platform apps places in a Workspace will now also default to being simple clients
  packages/web-platform/src/factory.ts
  packages/web-platform/src/fallbacks/core.ts
Labels: tag: bug fix, tag: enhancement
