Repository Glue42/core, pull requests merged in 2023-01, with the labels that each got.

#620 Fixes various core seed project issues
  packages/dev-workspaces-frame/src/App.tsx
  packages/dev-workspaces-frame/src/index.tsx
  packages/web-platform/src/controllers/glue.ts
  packages/web-platform/src/controllers/main.ts
  packages/web/src/layouts/controller.ts
Labels: tag: bug fix

#626 Refactors the intents resolver spawn bounds function
  packages/web/changelog.md
  packages/web/src/intents/controller.ts
Labels: tag: bug fix

#589 Add Support for Init as Empty Workspaces Frame for Platforms
  packages/web-platform/platform.d.ts
  packages/web-platform/src/controllers/system.ts
  packages/web-platform/src/platform.ts
  packages/web-platform/src/shared/decoders.ts
  packages/workspaces-ui-core/src/interop/platformCommunicator.ts
  packages/workspaces-ui-core/src/interop/types.ts
  packages/workspaces-ui-core/src/layouts.ts
  packages/workspaces-ui-core/src/manager.ts
Labels: tag: new feature

#632 Added a Requirements & Compatibility section.
  docs/getting-started/01_what-is-glue42-core/overview.md
  docs/getting-started/02_what-is-glue42-core-plus/overview.md
  docs/getting-started/03_requirements-compatibility/config.json
  docs/getting-started/03_requirements-compatibility/requirements-compatibility.md
  docs/getting-started/04_quick-start/quick-start.md
  docs/getting-started/05_project-deployment/deployment.md
  docs/getting-started/06_fdc3-compliance/config.json
  docs/getting-started/06_fdc3-compliance/fdc3-compliance.md
  docs/getting-started/07_faq/config.json
  docs/getting-started/07_faq/faq.md
Labels: tag: documentation

#634 Expose isSelected property for Workspace Windows
  packages/workspaces-api/changelog.md
  packages/workspaces-api/src/models/window.ts
  packages/workspaces-api/workspaces.d.ts
Labels: tag: new feature

#635 Improve the frame global layout behavior
  packages/golden-layout/index.d.ts
  packages/web-platform/src/common/types.ts
  packages/web-platform/src/controllers/glue.ts
  packages/web-platform/src/fallbacks/core.ts
  packages/web-platform/src/libs/applications/controller.ts
  packages/web-platform/src/libs/applications/decoders.ts
  packages/web-platform/src/libs/layouts/controller.ts
  packages/web-platform/src/libs/layouts/types.ts
  packages/web-platform/src/libs/windows/controller.ts
  packages/web-platform/src/libs/workspaces/controller.ts
  packages/web-platform/src/libs/workspaces/decoders.ts
  packages/web-platform/src/libs/workspaces/frames.ts
  packages/web-platform/src/libs/workspaces/types.ts
  packages/web-platform/src/shared/decoders.ts
  packages/web/src/appManager/controller.ts
  packages/web/src/appManager/protocol.ts
  packages/web/src/shared/decoders.ts
  packages/web/src/windows/controller.ts
  packages/web/web.d.ts
  packages/workspaces-api/src/communication/constants.ts
  packages/workspaces-api/src/controllers/base.ts
  packages/workspaces-api/src/controllers/main.ts
  packages/workspaces-api/src/models/workspace.ts
  packages/workspaces-api/src/shared/decoders.ts
  packages/workspaces-api/src/types/controller.ts
  packages/workspaces-api/src/types/protocol.ts
  packages/workspaces-api/workspaces.d.ts
  packages/workspaces-ui-core/src/config/factory.ts
  packages/workspaces-ui-core/src/interop/facade.ts
  packages/workspaces-ui-core/src/interop/types.ts
  packages/workspaces-ui-core/src/layout/controller.ts
  packages/workspaces-ui-core/src/layout/eventEmitter.ts
  packages/workspaces-ui-core/src/layouts.ts
  packages/workspaces-ui-core/src/manager.ts
  packages/workspaces-ui-core/src/state/resolver.ts
  packages/workspaces-ui-core/src/state/workspaceWrapper.ts
  packages/workspaces-ui-core/src/uiExecutor.ts
  packages/workspaces-ui-core/src/utils/index.ts
Labels: tag: bug fix

#640 Improve the Platform-Platform detection
  packages/web-platform/src/common/defaultConfig.ts
  packages/web-platform/src/fallbacks/core.ts
  packages/web-platform/src/libs/workspaces/frames.ts
Labels: tag: enhancement
