Repository Glue42/core, pull requests merged in 2023-02, with the labels that each got.

#645 Update all packages to @glue42/desktop@5.18.2
  .npmrc
  packages/dev-workspaces-frame/package-lock.json
  packages/ng/package-lock.json
  packages/ng/package.json
  packages/react-hooks/package-lock.json
  packages/web-platform/package-lock.json
  packages/web-platform/package.json
  packages/web/package-lock.json
  packages/web/package.json
  packages/workspaces-ui-react/package-lock.json
Labels: tag: internal

#651 Update ws to 8.12.1 in @glue42/core
  packages/core/changelog.md
  packages/core/package-lock.json
  packages/core/package.json
Labels: tag: bug fix

#653 [Experimental] Enable full support web-platform and workspaces to be hosted as iframes inside non-Glue clients
  packages/core/src/connection/transports/webPlatform.ts
Labels: tag: new feature

#647 Typo fix - changed chapter 1.5 to 1.4
  tutorials/guides/02_react/react.md
Labels: tag: documentation

#656 Add Themes API to Web
  e2e/config.js
  e2e/tests/themes/getCurent.spec.js
  e2e/tests/themes/list.spec.js
  e2e/tests/themes/onChanged.spec.js
  e2e/tests/themes/select.spec.js
  packages/web-platform/changelog.md
  packages/web-platform/src/common/types.ts
  packages/web-platform/src/controllers/domains.ts
  packages/web-platform/src/controllers/main.ts
  packages/web-platform/src/libs/notifications/controller.ts
  packages/web/changelog.md
  packages/web/src/communication/bridge.ts
  packages/web/src/communication/constants.ts
  packages/web/src/shared/decoders.ts
  packages/web/src/shared/ioc.ts
  packages/web/src/shared/types.ts
  packages/web/src/themes/controller.ts
  packages/web/src/themes/protocol.ts
  packages/web/src/windows/controller.ts
  packages/web/web.d.ts
Labels: tag: new feature

#658 Extend the Notifications API
  e2e/tests/notifications/clear.spec.js
  e2e/tests/notifications/clearAll.spec.js
  e2e/tests/notifications/click.spec.js
  e2e/tests/notifications/list.spec.js
  e2e/tests/notifications/onClosed.spec.js
  e2e/tests/notifications/onRaised.spec.js
  e2e/tests/notifications/raise.spec.js
  packages/web-platform/changelog.md
  packages/web-platform/platform.d.ts
  packages/web-platform/src/common/defaultConfig.ts
  packages/web-platform/src/common/types.ts
  packages/web-platform/src/controllers/serviceWorker.ts
  packages/web-platform/src/controllers/session.ts
  packages/web-platform/src/libs/notifications/controller.ts
  packages/web-platform/src/libs/notifications/decoders.ts
  packages/web-platform/src/libs/notifications/types.ts
  packages/web-platform/src/shared/decoders.ts
  packages/web-worker/changelog.md
  packages/web-worker/src/worker.ts
  packages/web/changelog.md
  packages/web/src/notifications/controller.ts
  packages/web/src/notifications/notification.ts
  packages/web/src/notifications/protocol.ts
  packages/web/src/shared/decoders.ts
  packages/web/src/shared/ioc.ts
  packages/web/web.d.ts
Labels: tag: new feature

#660 Added support for different themes in workspaces-ui-core
  packages/workspaces-ui-core/changelog.md
  packages/workspaces-ui-core/src/layout/themeController.ts
  packages/workspaces-ui-core/src/manager.ts
  packages/workspaces-ui-core/src/uiExecutor.ts
Labels: tag: new feature
