Repository Glue42/core, pull requests merged in 2023-04, with the labels that each got.

#703 Improve the platform discovery.
  packages/core/changelog.md
  packages/core/src/connection/transports/webPlatform.ts
  packages/web-platform/changelog.md
  packages/web-platform/src/common/types.ts
  packages/web-platform/src/connection/portsBridge.ts
  packages/web-platform/src/controllers/main.ts
  packages/web-platform/src/libs/extension/controller.ts
  packages/web-platform/src/libs/extension/decoders.ts
  packages/web-platform/src/libs/extension/types.ts
  packages/web-platform/src/libs/windows/controller.ts
  packages/web-platform/src/libs/windows/types.ts
  packages/web/changelog.md
  packages/web/src/appManager/controller.ts
  packages/web/src/shared/ioc.ts
  packages/web/src/windows/controller.ts
Labels: tag: bug fix, tag: enhancement, tag: new feature

#705 Validate the legacy protocol support of the Search API
  e2e/config.js
  e2e/config/apps/coreSupport/index.html
  e2e/config/apps/coreSupport/index.js
  e2e/config/gtf/app.ts
  e2e/config/gtf/gtf.d.ts
  e2e/tests/search/legacy.spec.js
  e2e/tests/search/registerProvider.spec.js
  packages/core/changelog.md
  packages/core/src/connection/transports/webPlatform.ts
  packages/search-api/changelog.md
  packages/search-api/src/controllers/client.ts
  packages/search-api/src/controllers/glue.ts
  packages/search-api/src/controllers/provider.ts
  packages/search-api/src/index.ts
  packages/search-api/src/services/limits-tracker.ts
  packages/search-api/src/shared/ioc.ts
Labels: tag: enhancement

#707 Restoring a hibernated workspace now also restores the last known window contexts and workspace context
  e2e/tests/workspaces/Workspace/resume.spec.js
  packages/web-platform/changelog.md
  packages/web-platform/src/common/types.ts
  packages/web-platform/src/controllers/glue.ts
  packages/web-platform/src/libs/windows/controller.ts
  packages/web-platform/src/libs/workspaces/controller.ts
  packages/web-platform/src/libs/workspaces/decoders.ts
  packages/web-platform/src/libs/workspaces/types.ts
  packages/workspaces-ui-core/changelog.md
  packages/workspaces-ui-core/src/app/factory.ts
  packages/workspaces-ui-core/src/interop/platformCommunicator.ts
  packages/workspaces-ui-core/src/manager.ts
Labels: tag: bug fix

#712 FDC3 fix expecting of iframes to always have glue window
  e2e/config/apps/iframe/app/index.html
  e2e/config/apps/iframe/app/index.js
  e2e/config/apps/iframe/index.html
  e2e/tests/fdc3/DesktopAgent/addContextListener.spec.js
  packages/fdc3/src/channels/controller.ts
  packages/fdc3/src/controllers/applications.ts
  packages/fdc3/src/controllers/glue.ts
  packages/fdc3/src/shared/utils.ts
  packages/fdc3/src/types/fdc3Types.d.ts
  packages/fdc3/src/types/glue42Types.d.ts
Labels: tag: bug fix
